# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170122_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Ответ')),
                ('is_True', models.BooleanField(verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name_plural': 'Ответы',
                'verbose_name': 'Ответ',
            },
        ),
        migrations.CreateModel(
            name='nametest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('test_summa', models.FloatField(default=0, verbose_name='Сумма баллов для сдачи теста')),
                ('time_of_test', models.IntegerField(default=0, verbose_name='Время, мин:')),
                ('poryad', models.BooleanField(default=False, verbose_name='Вопросы по порядку')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Тесты',
                'verbose_name': 'Тесты ',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('summa', models.IntegerField(default=0, verbose_name='Сумма')),
                ('tip', models.BooleanField(default=False, verbose_name='Несколько правильных ответов')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.nametest')),
            ],
            options={
                'verbose_name_plural': 'Вопросы',
                'verbose_name': 'Вопрос',
            },
        ),
        migrations.CreateModel(
            name='results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(default=0)),
                ('test', models.IntegerField(default=0)),
                ('one_pop', models.NullBooleanField(verbose_name='Первая попытка')),
                ('two_pop', models.NullBooleanField(verbose_name='Вторая попытка')),
                ('nomer_pop', models.IntegerField(default=0)),
                ('one_pop_bal', models.FloatField(default=0, verbose_name='Баллов в первой попытке')),
                ('two_pop_bal', models.FloatField(default=0, verbose_name='Баллов во второй попытке')),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ab', models.IntegerField(default=0)),
                ('id_testa', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Question'),
        ),
    ]
